### ISSUE TITLE
Change language parameter with plugin

### ISSUE THREAD

**Issue by Rtransat** [php-tmdb/laravel#12]
Hi,

Great package for tmdb integration with laravel :)

I've tried to change the language from the api to [French](https://github.com/php-tmdb/laravel#registering-plugins) (fr) but I've still the data in English.

I've also tried [this](https://github.com/php-tmdb/api#general-api-usage) but is not working with language parameter :/

Thx

**Comment by MarkRedeman** [comment]
I've probably have found why it's not working, will try to fix it tonight.

**Comment by MarkRedeman** [comment]
@Rtransat can you confirm that this is fixed?

**Comment by Rtransat** [comment]
Still not fixed :/

**Comment by MarkRedeman** [comment]
Did you update the version? Maybe your cache isn't cleared?
I tried it using a Dutch filter which worked on my laptop.

**Comment by Rtransat** [comment]
Yes it's updated, I have clear the config cache, application cache and dump autoload from composer. But nothing new :/

```php
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Tmdb\HttpClient\Plugin\LanguageFilterPlugin;

class AppServiceProvider extends ServiceProvider {

	/**
	 * Bootstrap any application services.
	 *
	 * @return void
	 */
	public function boot()
	{
		//
	}

	/**
	 * Register any application services.
	 *
	 * @return void
	 */
	public function register()
	{
		$plugin = new LanguageFilterPlugin('fr');
		$client = $this->app->make('Tmdb\Client');
		$client->getHttpClient()->addSubscriber($plugin);
	}
}

```

**Comment by MarkRedeman** [comment]
@Rtransat I will add a note that clearly states that you have to use the boot method. It's quite easy to ignore the current message.
