### ISSUE TITLE
Issues with API Key

### ISSUE THREAD

**Issue by pedrommone** [php-tmdb/laravel#13]
I just install with composer on laravel 4.2 and every request I do I get invalid key error.

```
Config::set('tmdb-package::tmdb.api_key', $_ENV['TMDB_API']);

var_dump( Tmdb::getMoviesApi()->getMovie( 300 ) );
```

Made this workaround and worked. The config file is returning blank.

**Comment by MarkRedeman** [comment]
I forgot to configure the Laravel 4 service provider after renaming the package. Can you confirm that it is fixed after the latest commit?

**Comment by pedrommone** [comment]
Fixed, thank you.
