### ISSUE TITLE
How do i handle errors ?

### ISSUE THREAD

**Issue by DeeJaVu** [php-tmdb/laravel#18]
because when /movie/0 does not exist it returns a TmdbApiException
is there a way to show a custom error page ?

**Comment by wtfzdotnet** [comment]
Read up on try catch blocks :)

**Comment by DeeJaVu** [comment]
im doing that almost 24 hours, ik ben noob

**Comment by wtfzdotnet** [comment]
```
try {
   ... code ...
}
catch(TmdbApiException $e){
   ... handel fout af ...
}

**Comment by DeeJaVu** [comment]
riiiight echt bedankt je bent de beste
