### ISSUE TITLE
Person credit order

### ISSUE THREAD

**Issue by rifats** [php-tmdb/laravel#20]
Tell me please how to get the cast and crew records for Person in the right order (by year)? By default getCombinedCredits, getTvCredits and getMovieCredits methods do not return them in correct order.
Many thanks.

**Comment by wtfzdotnet** [comment]
Hi @rifats ,

I've only noticed your ticket earlier and took a look under the hood of our main libray `php-tmdb/api`. This functionality was not present yet but thanks to this https://github.com/php-tmdb/api/commit/55dc12fec4c18679099761ca23a062a89a4a05ac commit you can now sort any collection. 

So please make sure you have version `2.0.11` of the `php-tmdb/api` library installed, then try the following:
```
$person->sort(function($a, $b){
    if ($a->getReleaseDate() == $b->getReleaseDate()) {
        return 0;
    }

    return $a->getReleaseDate() > $b->getReleaseDate() ? 1 : -1;
});
```

Have a great weekend!

**Comment by rifats** [comment]
@wtfzdotnet , thank you for the hint!
I realized that the API does not implement sorting. And yesterday I did so (for CombinedCredits):

```
usort($credits['cast'],  array($this, "compareReleaseDate"));

function compareReleaseDate($a, $b)
    {
        $a_date = (array_key_exists('release_date', $a)) ? $a['release_date'] : $a['first_air_date'];
        $b_date = (array_key_exists('release_date', $b)) ? $b['release_date'] : $b['first_air_date'];
        return strnatcmp($b_date,$a_date);
    }
```
