### ISSUE TITLE
configuration not published - laravel 5

### ISSUE THREAD

**Issue by Zaifor** [php-tmdb/laravel#21]
tmdb.php isnt published in {Laravel}/config folder

php artisan vendor:publish --provider=php-tmdb/laravel
Nothing to publish for tag [].

Laravel Framework version 5.1.16 (LTS)
I'm using Homestead on windows 10 if it is important.

if I create tmdb.php in /config its working ok.

**Comment by wtfzdotnet** [comment]
@markredeman could you shed some light on this? :)

**Comment by Zaifor** [comment]
if I'm not mistaken vendor:publish must create tmdb.php file in Laravel's /config folder. 

With fresh laravel 5.1 installation i'm fallowing the README: require the package, add the service provider to app.php and run php artisan vendor:publish --provider=php-tmdb/laravel. 

Than the README says: "Next you can modify the generated configuration file tmdb.php accordingly."

But theres no such a file for me at /config. I had to create this file manually. The only tmdb.php file in my project is located in \vendor\php-tmdb\laravel\src\config

**Comment by Zaifor** [comment]
Ok, just "php artisan vendor:publish" its working as expeced with 5.1.

Copied File [/vendor/php-tmdb/laravel/src/config/tmdb.php] To [/config/tmdb.php]

**Comment by mattkloc** [comment]
Thank You Zaifor. I had the same issue.

**Comment by wtfzdotnet** [comment]
Hey guys,

I'm not a laravel guy at all and the maintainer of this repo is @markredeman, is it possible for you guys to send a pull request to update documentation or even the code itself to fix this?

I'll be happy to merge in some improvements.

Thanks

**Comment by MarkRedeman** [comment]
Sorry for the late reply, I've updated the readme. The command should have been:
```
php artisan vendor:publish --provider="Tmdb\Laravel\TmdbServiceProviderLaravel5"
```

Just `php artisan vendor:publish` will also work, but it will also publish configurations from other packages.
