### ISSUE TITLE
[L5.2] Update composer.json

### ISSUE THREAD

**Issue by Rtransat** [php-tmdb/laravel#23]
Can you update your composer.json to update the event-dispatcher package to v3.0 ?

**Comment by wtfzdotnet** [comment]
Could you create a fork with this update and submit a pull request for @MarkRedeman to review? I'm not involved with Laravel so I have no clue what implications there are for backwards compatibility.

**Comment by MarkRedeman** [comment]
This is currently not possible because [TMDB/API](https://github.com/php-tmdb/api/blob/2.0/composer.json#L18) depends on version `~2.4`.
@wtfzdotnet I did a quick check and it seems that all unit tests are passing when the version of `symfony/event-dispatcher` is upgraded to `~3.0`. Could you verify that it is safe to upgrade to version 3?

**Comment by MarkRedeman** [comment]
@Rtransat Is there any reason why you need version 3? I've tested the package with Laravel 5.2 and it seems to work out of the box. Are there other packages that require version 3?

**Comment by Rtransat** [comment]
I can't check right now but last night composer tellîg me an error with composer require command about an error with envent dispatacher 2.0. It need to install event dispatcher v2 to install the package.

**Comment by MarkRedeman** [comment]
Then I guess there is some other package that you're using that requires v3.

I've updated PR #25 to change the dependency of `event-dispatcher` to `~2.8|~3.0`, which I will probably merge tonight.

**Comment by Rtransat** [comment]
It was a fresh install of laravel and php-tmdb/laravel was the first package I've installed in my new laravel installation.

**Comment by Rtransat** [comment]
I just retry and everything works perfectly, no errors with composer. I don't know why composer throw an error yesterday.

**Comment by MarkRedeman** [comment]
That's quite weird, maybe someone changed its dependencies?

I've updated PR #25 so that it will be fully compatible with `event-dispatcher` v3.0.

**Comment by MarkRedeman** [comment]
@Rtransat I've released a new version that is compatible with v3, so I'm closing this issue.
