### ISSUE TITLE
Deprecate L4 and require PHP 5.6

### ISSUE THREAD

**Issue by MarkRedeman** [php-tmdb/laravel#26]
I'm considering to no longer support Laraval 4 with release 2.0.0, and change the PHP requirement to 5.6.
This would make maintaining this package somewhat easier.

Since I'm not using this package for any projects of my own I would like to get some input from its users. Is there anyone who is using Laravel 4 with this package?

**Comment by laravelish** [comment]
do people still use L4 !

**Comment by wtfzdotnet** [comment]
Closing this issue seeing the age of it...
