### ISSUE TITLE
Error when following instructions

### ISSUE THREAD

**Issue by notflip** [php-tmdb/laravel#3]
Call to undefined method Tmdb\Api\Movies::load()

I'm trying to test this out in laravel using:
I followed the instruction on this page

    Route::get('/', function()
    {
	    $client = Tmdb::getMoviesApi()->load(13);
	    return $client;
    });

**Comment by wtfzdotnet** [comment]
Could you give the Repository methods a try? I'm not sure what's causing this, I'll have to check at home later tonight.

**Comment by notflip** [comment]
Thanks for your response, It's producing the same error. Do i have to include anything at the top for laravel? or a use .. ?

**Comment by wtfzdotnet** [comment]
I'm not familiar at all with laravel, this package was a best effort, try debugging the tmdb class in this repository to see what's going?

**Comment by notflip** [comment]
I will give it a try! Thank you

2015-01-22 16:12 GMT+01:00 Michael Roterman <notifications@github.com>:

**Comment by MarkRedeman** [comment]
@notflip did you solve this issue? (if not, try the new version)

**Comment by notflip** [comment]
I've got it fixed using the new version. Thanks!

**Comment by notflip** [comment]
U bent uitgenodigd!

Met Airbnb kun je unieke accommodaties bij lokale verhuurders ontdekken, over de hele wereld.
Het is simpel, meld je voor 20 mei 2015 aan om €22 korting te krijgen op je eerste reis van €89 of meer.


Accepteer Uitnodiging
http://www.airbnb.be/c/mstevens1?euid=d3a47a24-0fb8-43bc-e149-deddacab01b0&ri=18292375&s=1

Bedankt,
Het Airbnb Team

Postbus 410807, San Francisco, CA 94121

Afmelden
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAzZjQ0ZDA1NmY1YmQyMmY4NzMzMGRmNTI3MDhiM2UyNjU0YTMzNDZkNTVlYmVmOTJjZjAwMDAwMDAxMTBkOGQ1NTA5MmExNjljZTAzNDliNzc0QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiJkM2E0N2EyNC0wZmI4LTQzYmMtZTE0OS1kZWRkYWNhYjAxYjAifQ==&mac=7UDCjyCxBECHpGUVJ6NimS9Esqk=

### Airbnb ###
