### ISSUE TITLE
Level is not defined in Logger.php

### ISSUE THREAD

**Issue by rifats** [php-tmdb/laravel#31]
Hello!
There is an error after updating:
`
InvalidArgumentException in Logger.php line 461: Level "" is not defined, use one of: 100, 200, 250, 300, 400, 500, 550, 600
`

`
in Logger.php line 461
`
`
at Logger::getLevelName(null) in Logger.php line 292
`
`
at Logger->addRecord(null, 'pc wtfzdotnet/php-tmdb-api (v2.1.4) - [08/Nov/2016:13:45:53 +0000] "GET /3/configuration?api_key=xxxxxx HTTP/1.1" NULL NULL', array('request' => object(Request), 'response' => null, 'reason' => null)) in Logger.php line 517
`
`
at Logger->log(null, 'pc wtfzdotnet/php-tmdb-api (v2.1.4) - [08/Nov/2016:13:45:53 +0000] "GET /3/configuration?api_key=xxxxxx HTTP/1.1" NULL NULL', array('request' => object(Request), 'response' => null, 'reason' => null)) in Logger.php line 137
`

There is a line in config/app.php:
`'log_level' => env('APP_LOG_LEVEL', 'debug'),`

**Comment by Fatih90** [comment]
hi i once got exactly the same error and while i was searching for help, i upgraded my laravel using composer update, and the error was gone, what version of laravel are you using ?
i am using `Laravel Framework version 5.3.22`

**Comment by rifats** [comment]
Fatih90, hi!
The same version - 5.3.22. Two month ago I updated from 5.2 by following the guide https://laravel.com/docs/5.3/upgrade
Maybe something missed. I'll check again.

**Comment by MarkRedeman** [comment]
Do you think you two can figure out what's wrong and make a pull request? Though I'm the maintainer of this package I'm not using it so debugging is difficult / would take quite some time.

--- 
What's the value of your `APP_LOG_LEVEL` entry in your `.env` file?

**Comment by rifats** [comment]
`APP_LOG_LEVEL=debug`
I must first check the upgrade process. Maybe it's my fault.

**Comment by Fatih90** [comment]
@rifats try it in a new laravel installation usin the laravel installer: `laravel new app`

or share you code where this error happens and i will see if i get the same error

**Comment by rifats** [comment]
@Fatih90 it is Tmdb\Helper\ImageHelper
In controller's __construct
```
    function __construct(MovieRepository $movieRepository,
                         MovieEntityManager $movieEntityManager,
                         CreditEntityManager $creditEntityManager,
                         MovieCreditManager $movieCreditManager,
                         ImageHelper $helper,
                         UpdateChecker $updateChecker)
    {
        $this->movieRepository      = $movieRepository;
        $this->movieEntityManager   = $movieEntityManager;
        $this->creditEntityManager  = $creditEntityManager;
        $this->movieCreditManager   = $movieCreditManager;
        $this->helper               = $helper;
        $this->updateChecker        = $updateChecker;
    }
```
or in blade:
```
@inject('image', 'Tmdb\Helper\ImageHelper')
```

**Comment by Fatih90** [comment]
@rifats 

it works just fine, did you try it on a brand new installation of laravel

![image](https://cloud.githubusercontent.com/assets/22959827/20155852/17373b78-a6ce-11e6-866f-d8f5f0ef9304.png)

**Comment by rifats** [comment]
I created a new project, a test controller for tmdb - works fine. So it must be some mistake of upgrade process. I'll copy the files of my project to the new one. @Fatih90 thank you for participating.

**Comment by rifats** [comment]
@Fatih90, hi!
Do you have log enabled in config/tmdb.php?

**Comment by Fatih90** [comment]
@rifats  ya i do

**Comment by okaufmann** [comment]
Any news for this bug?

I think it has something to do with the cache plugin: https://github.com/rtheunissen/guzzle-log-middleware

The logging level will be set here:
https://github.com/php-tmdb/api/blob/857e6f6541582d7275e608ab4232e479e151b852/lib/Tmdb/HttpClient/HttpClient.php#L488

**Comment by rifats** [comment]
@okaufmann Yes, I followed up this line, but do not know how to solve issue. I disabled caching to continue working.
