### ISSUE TITLE
Remove language for specific requests?

### ISSUE THREAD

**Issue by marleybobby** [php-tmdb/laravel#34]
I need to remove the language parameter for some requests, e.g. PeopleRepository to receive the biography.

I set it as mentioned in the readme. But how to remove it for a single request? 

Greetings

**Comment by yukoff** [comment]
@marleybobby, could you be more specific? Some examples would also be useful. BTW, are you sure this issue is related to `php-tmdb/laravel`?

**Comment by marleybobby** [comment]
@yukoff I'm not a 100% sure that this is the right place to ask but 90%, but becuse I'm using your wrapper for the tmdb-api it appeared the right section for me.

I register the `LanguageFilterPlugin` as suggested in your Readme.

```php
class TmdbServiceProvider extends ServiceProvider {

    /**
     * Add a Dutch language filter to the Tmdb client
     *
     * @return void
     */
    public function boot()
    {
        $plugin = new LanguageFilterPlugin('nl');
        $client = $this->app->make('Tmdb\Client');
        $client->getHttpClient()->addSubscriber($plugin);
    }

    /**
     * Register services
     * @return void
     */
    public function register()
    {
        // register any services that you need
    }
}
```

Then I make a request like: 

´´´php
// Get an actor
$repository = App::make(PeopleRepository::class);
// Hook in to change the language back to english???
$person = $repository->load($request->input('tmdbId'));
´´´

But here I don't know how to "hook" in and change the language or assign a new `LanguageFilterPlugin`. 

I tried:
```php
$repository->load($request->input('tmdbId'), ['append_to_response' => 'images', 'language' => 'en']);
```

but without success.

**Comment by wtfzdotnet** [comment]
This question has been buried under a tomb for a while, I will be looking into this tomorrow but I am afraid the solution you would have had to bring up is a little bit messy messing around with the observers present.
