### ISSUE TITLE
Doesn't work with Laravel 5.

### ISSUE THREAD

**Issue by crazydc** [php-tmdb/laravel#5]
Seems Laravel have upgraded the Illuminate/support to 5.0.13. I will try and create a new dev branch of this and test it with Laravel 5.

**Comment by notflip** [comment]
Hi,

I managed to change how laravel 5 loads the config variables.

https://github.com/wtfzdotnet/tmdb-package/compare/master...notflip:dev-laravel-5?expand=1

**Comment by notflip** [comment]
I managed to change how Laravel 5 loads the config. 

https://github.com/wtfzdotnet/tmdb-package/pull/8

**Comment by wtfzdotnet** [comment]
@crazydc could you possibly give me some feedback if this fixes it? If so I'll merge it in for now, I found a forum topic where @notflip posted and asked a community member @markredeman to help out fix this package for you laravel users out there.

**Comment by crazydc** [comment]
I couldn't figure out how I can use composer to install my own branch to test it correctly. 

I was manually hacking it into my code and could not get it to play nice. The configuration part that @notflip mentions looks like it would work. I personally have not tested. I will copy code manually into my Dev branch and see if it gets it work.

Any hints on how I can use composer to install private branch would be great.

**Comment by notflip** [comment]
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/notflip/tmdb-package"
        }
    ],
    "require": {
        "wtfzdotnet/tmdb-package": "dev-dev-laravel-5"
    }
}

And yes i thought you had to type the dev part yourself so now it's dev-dev :)

**Comment by MarkRedeman** [comment]
@crazydc Laravel 5 support has been added in the new version.
