### ISSUE TITLE
Service provider auto discovery support not working

### ISSUE THREAD

**Issue by SquareBeard** [php-tmdb/laravel#54]
The service provider auto discovery is not registering the proper provider.
It registers the `TmdbServiceProviderLaravel5` provider instead of `TmdbServiceProvider`.
This prevent the API from working because the `Tmdb\Client` singleton is not setup.

Registering the provider manually fix the problem.

**Comment by laravelish** [comment]
you will never get a response my friend believe me !
they will never fix it or merge your pull request

this project is dead someone else needs to maintain it

**Comment by z38** [comment]
@SquareBeard Thank you for the report and the steps to fix the issue. I think the auto discovery should work correctly after applying #55.

@laravelish Don't despair! ;) Pull-requests are still welcome and we will do our best to review them.
