### ISSUE TITLE
session token using Dependency injection

### ISSUE THREAD

**Issue by djvu61** [php-tmdb/laravel#56]
Hello i can use this code and it works 

```php
 $token = new \Tmdb\ApiToken(env('TMDB_API'));
 $client = new Client($token, ['session_token' => new \Tmdb\SessionToken(session('session_token'))]);
```

but i have to reuse this code everywhere if i want to do things with my account, 

my question is, is there i way to use this code using Dependency injection or other method

so i can use it in my AppServiceProvider

**Comment by djvu61** [comment]
hellooooooooooooo ????????????????????

**Comment by djvu61** [comment]
hellooooooooooooooooooooooooooooooooooooooooooo

**Comment by djvu61** [comment]
helloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by djvu61** [comment]
helloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by ghost** [comment]
bump
