### ISSUE TITLE
Not working with laravel 5.8

### ISSUE THREAD

**Issue by engelde** [php-tmdb/laravel#62]
Hello,

I am attempting to use this with laravel 5.8 but I receive the following error:
Call to undefined method Illuminate\Events\Dispatcher::fire()

I have read that this was replaced with the following in laravel 5.8:
Illuminate\Events\Dispatcher::dispatch() 

Is it possible that this will be updated in the future?

Thank you!

**Comment by celorodovalho** [comment]
+1

**Comment by Nielson** [comment]
If anyone runs into this problem, this can be fixed by changing a method name from "fire" to "dispatch" at line 49, so it looks like this:

```php    
public function dispatch($eventName, Event $event = null)
    {
        $this->laravelDispatcher->dispatch($eventName, $event);
        return $this->symfonyDispatcher->dispatch($eventName, $event);
    }
```

File:  vendor/php-tmdb/laravel/src/Adapters/EventDispatcherAdapter.php

**Comment by N3rdP1um23** [comment]
I've made the update to the file but I'm still not able to have the event occur when I retrieve data from TMDb.  Is there something that I'm missing?

How are you guy's implementing the event listening?

**Comment by Nielson** [comment]
> I've made the update to the file but I'm still not able to have the event occur when I retrieve data from TMDb. Is there something that I'm missing?
> 
> How are you guy's implementing the event listening?

Sorry for the late reply! 

Did you manage to fix this? If not, which error are you getting?

**Comment by N3rdP1um23** [comment]
> > I've made the update to the file but I'm still not able to have the event occur when I retrieve data from TMDb. Is there something that I'm missing?
> > How are you guy's implementing the event listening?
> 
> Sorry for the late reply!
> 
> Did you manage to fix this? If not, which error are you getting?

Oh that's okay.  I changed the files that was recommended but everytime an event it made, it is not captured.  I was just wondering where you placed a listener for TMDb events.

**Comment by N3rdP1um23** [comment]
@Nielson  Well, I figured out why the event wasn't being fired.  Little mishap on my end haha.  Just trying to parse the event response which is currently returning null.

Edit: Well, I capture the event and then I would like to perform some operations once I get the response from TMDb.  But, while the event is being captured, I try and access the response but the response is NULL.  When I check the TMDb log there are two requests per request.  The first one the response is null and then the second one displays that the response is an object.  I'm not sure if I've missed anything while capturing the events or even if I'm  going about it correct.  Any help would be greatly appriciated :)

**Comment by Nielson** [comment]
@N3rdP1um23 Could you please post the code that you fire when getting the response? A bit of code and if possible, a log would be really helpful :)

**Comment by N3rdP1um23** [comment]
@Nielson, Of course, haha, that would help, wouldn't it :)

**Controller**
```php
Tmdb::getMoviesApi()->getPopular();
```

**EventServiceProvider** under the boot method (will move it to a custom listener once everything is working under boot)
```php
Event::listen(TmdbEvents::REQUEST, function(RequestEvent $event) {
    Log::info("A request was made to TMDB");
    // do stuff with $event
   dd($event->hasResponse()); // returns false
   dd($event->getResponse()); // returns null
});
```
Once I can get that to work, like I said, I'll move it to my own listener to be handled there.  The dd's are just to show what I was testing and the response that I was getting is the value beside it.

**Log File**
```
[2019-07-03 00:48:35] php-tmdb-api.DEBUG: _LAPTOP_ GuzzleHttp/6.3.3 curl/7.59.0 PHP/7.2.8 - [03/Jul/2019:00:48:35 -0400] "GET /3/tv/1399?api_key=_API_KEY_ HTTP/1.1" NULL NULL {"request":"[object] (GuzzleHttp\\Psr7\\Request: {})","response":null,"reason":null} []
[2019-07-03 00:48:36] php-tmdb-api.DEBUG: _LAPTOP_ GuzzleHttp/6.3.3 curl/7.59.0 PHP/7.2.8 - [03/Jul/2019:00:48:36 -0400] "GET /3/tv/1399?api_key=_API_KEY_ HTTP/1.1" 200 6489 {"request":"[object] (GuzzleHttp\\Psr7\\Request: {})","response":"[object] (GuzzleHttp\\Psr7\\Response: {})","reason":null} []
```

So from the log, you can see that there are 2 requests, the first with the response of null and then the second one with the response as an object.

Let me know if you need anything else and thanks for the help!  It's very appreciated!!

**Comment by starfreck** [comment]
**I am using this package with Laravel 5.8 but it isn't working. Anyone can help me?**

![Screenshot from 2019-08-16 15-23-37](https://user-images.githubusercontent.com/15255654/63159852-feae1080-c039-11e9-9c5a-27517fb197fb.png)
![Screenshot from 2019-08-16 15-23-54](https://user-images.githubusercontent.com/15255654/63159856-ff46a700-c039-11e9-9663-ede2a3349a51.png)

**Comment by celorodovalho** [comment]
@vasuratanpara, check the @Nielson answer.
