### ISSUE TITLE
[BadMethodCallException] Call to undefined method [package] ( dev-laravel5)

### ISSUE THREAD

**Issue by notflip** [php-tmdb/laravel#7]
I found the error I was talking about with the Laravel5 branch.

When you try to publish the config it hits an exception because of the serviceprovider change in laravel5.

Is anyone here capable of changing the serviceprovider to the Laravel 5 method?
I'll try looking into it tomorrow.

**Comment by MarkRedeman** [comment]
@notflip this is fixed with the new version.
