### ISSUE TITLE
I found a working fork for Laravel 7/8

### ISSUE THREAD

**Issue by shstkvch** [php-tmdb/laravel#73]
This is working for me on Laravel 8: https://github.com/DariusIII/tmdb-laravel

**Comment by n0v3xx** [comment]
Oh great! Will this fork integrated in the original project?

**Comment by wtfzdotnet** [comment]
Anyone is free to volunteer to maintain "this original" repository, as per https://github.com/php-tmdb/laravel#looking-for-maintainers.
